# Site settings
title: Thompson Highland Homeowners Association
email: board@thha.org
description: > # this means to ignore newlines until "baseurl:"
  Thompson Highland Homeowners Association
  12101-12299 NW Thompson Rd
  Portland, OR 97229
  45.548306, -122.803044
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thhaorg.github.io" # the base hostname & protocol for your site
twitter_username: thhanotyet
github_username:  thhaorg

# Build settings
markdown: kramdown
